Algoritmo "Calculo de idade"

Var
ano , nasci, idade: INTEIRO


Inicio

   escreva ("Que anos nos estamos? ")
   Leia (ano)
   escreva ("Que Ano eu Nasci, ")
   Leia (nasci)
   idade <- ano - nasci
   escreval ("Em", ano, " voce tera a idade de ", idade, " anos.")
   se  (idade >= 21) entao
   Escreva ("E você ja atingiu a maioridade ")
   senao
   Escreva (" Você não atingiu a maioridade ")
   
   
   fimSe
   
   Fimalgoritmo